### PR TITLE
Feature: Improved search

### LINKED ISSUE #107: Search spotify artist/albums and playlist
The sidebar search would now return a list of some tracks/albums/artist and playlists (max 5 results for each) as well as a link to view more results for each type.

When a result is selected it will now send the user to a `artist/:id`/ `album/:id` or `playlist/:id` view where they can view more search results. Similar to how Spotify currently works.

### PR DESCRIPTION
**Pull request by bcmrbvm**
# Feature: Improved search

This PR expends the basic sidebar track search to now search albums and artists as well as tracks. There are also links to view more search results and view artist and albums in more detail to find tracks.

## PR includes:
- Artist search and detail view in `artists` and `artists/:id`
- Album search and detail view in `albums` and `albums/:id`
- Track search view in `tracks`
- Sidebar search now returns a concatenated list of top 3 artists, albums and tracks from search as well as links to view more results in each category

### Notes
I was planning to do playlist search and detail as well but this requires user to be logged into Spotify in the FE so this will come in a later PR.

Fixes #107

### CODE REVIEW

**Comment by jamesjwarren** [comment]
This is awesome! :smile: 

One minor styling issue I saw:
screenshot 2015-07-15 15 34 18

**Comment by bcmrbvm** [comment]
thanks will take a look

**Comment by bcmrbvm** [comment]
@jamesjwarren should be fixed now

**Comment by jamesjwarren** [comment]
LGTM :+1:

**Pull request merged**
