### PR TITLE
Feature: hide controls for unauthorised user

### LINKED ISSUE #153: Player controls should be hidden when logged out
Currently playback controls are visible when logged out, they should probably be hidden as this is logged in functionality only.

*Note: When pause is clicked and the user is logged out, the timer and play/pause button enter the `paused` state despite an alert saying "you need to be logged in to do that".*

### PR DESCRIPTION
**Pull request by jamesjwarren**
Fixes #153

### CODE REVIEW

**Comment by bcmrbvm** [comment]
:+1:

**Comment by jamesjwarren** [comment]
This is failing e2e as the tests are performed without auth. We probably need some way to mock auth in tests.

**Comment by jamesjwarren** [comment]
@bcmrbvm E2E now fixed with a login helper and shrunk the controls container when they are hidden.

**Comment by bcmrbvm** [comment]
:+1:

**Pull request merged**
