### PR TITLE
Feature: Delete track

### LINKED ISSUE #100: New field in queue
In order to remove track from the queue we have to make each item in the queue unique. We've added new field into queue item 'uuid' which has to be used for removing items in queue:

```json
[
    {
        "track": {
            "album": {
                "id": "7f8bda77-5364-4902-9a98-208f1cdd7643",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/7928fc9bd902b917aae0ef1bee41cb51598a2d27",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/e80cb4d324d16881e2f7653abdbd70497bbab68d",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/bf567406035a8e2b162c6a23470c6cdd5dd560f3",
                        "width": 64
                    }
                ],
                "name": "Showtime, Storytime",
                "uri": "spotify:album:1tZlCjdI2dcfBXP8iSDsSI"
            },
            "artists": [
                {
                    "id": "26556f7e-3304-4e51-8243-dd2199fcf6fa",
                    "name": "Nightwish",
                    "uri": "spotify:artist:2NPduAUeLVsfIauhRwuft1"
                }
            ],
            "duration": 272906,
            "id": "4b170737-017c-4e85-965c-47b8a158c789",
            "name": "Dark Chest Of Wonders - Live @ Wacken 2013",
            "uri": "spotify:track:6FshvOVICpRVkwpYE5BYTD"
        },
        "user": {
            "avatar_url": "https://lh5.googleusercontent.com/-8zjhd-e4yZA/AAAAAAAAAAI/AAAAAAAAAFU/NiS1oH4gAKo/photo.jpg",
            "display_name": "Chris Reeves",
            "family_name": "Reeves",
            "given_name": "Chris",
            "id": "8258be6b-ee53-4186-8bbd-55bc0a3a6f24"
        },
        "uuid": "16fd2706-8baf-433b-82eb-8c7fada847da"
    }
    ...
]
```

### PR DESCRIPTION
**Pull request by edwardoparearyee**
Added delete track option to track to allow user to delete track from playlist

Fixes #100, #101 

### Note
API updated now to work with this

### CODE REVIEW

**Comment by jamesjwarren** [comment]
:+1:

**Comment by bcmrbvm** [comment]
Currently waiting for this API PR to be merged https://github.com/thisissoon/FM-API/pull/56

**Comment by edwardoparearyee** [comment]
Updated this as I missed a few things like the deleted event handler. I also fixed a few bugs and added more tests.

**Comment by edwardoparearyee** [comment]
@jamesjwarren could you have a look at this too when you get a chance

**Comment by jamesjwarren** [comment]
Cool :+1:

**Pull request merged**
