### PR TITLE
Feature: e2e tests

### PR DESCRIPTION
**Pull request by jamesjwarren**
This PR adds an e2e test for the history view with a test for infinite scroll pagination. #95 

The test checks 4 pages worth and ensures a 5th page is not loaded. Bizarrely this test passes despite there still being issues in production.

@bcmrbvm I couldn't get the e2e tests running on circle... is there something more that needs doing besides adding `grunt e2e` to the circle config 9053941

### CODE REVIEW

**Comment by bcmrbvm** [comment]
@jamesjwarren the e2e test should just run on circle with the `grunt e2e` command. Try running just FF in the tests and see if that works. There were some issues with running protractor with chrome in circle last time i checked.

**Comment by jamesjwarren** [comment]
Added some more e2e tests for playlist view and the track timer.

**Comment by bcmrbvm** [comment]
cool but does this fix the problem with history pagination? or do you think this is an angular issue or api issue?

**Comment by jamesjwarren** [comment]
No this doesn't fix the problem. The API seems to be returning the right headers, but I think I need to do some more debugging with the API locally.

**Comment by bcmrbvm** [comment]
sounds like a FE issue then, maybe try to break the problem down into it's simplest form in a jsfiddle or plunkr

**Comment by jamesjwarren** [comment]
@bcmrbvm is it ok to merge these e2e tests? Pagination issue will be fixed in https://github.com/thisissoon/FM-API/pull/41

**Comment by bcmrbvm** [comment]
@jamesjwarren merge away!

**Pull request merged**
