### PR TITLE
Feature: alerts

### LINKED ISSUE #63: Re-add error messages

### PR DESCRIPTION
**Pull request by jamesjwarren**
# Feature: Alerts

This PR includes:
- `FM.alert` module
- Generic alert for in-view 401 errors
- Fixes #63 

`FM.alert` provides `AlertService` which can be used to set alerts like:
```
AlertService.set("Woah there! You Need to login to do that.", "warning");
```

### CODE REVIEW

**Comment by eopa** [comment]
:+1: LGTM

**Comment by eopa** [comment]
@jamesjwarren do you need to include any tests?

**Comment by jamesjwarren** [comment]
@eopa tests are complete now, should be ready to merge

**Comment by eopa** [comment]
:+1:

**Pull request merged**
